### PR TITLE
Added multiple selection on "Structures" combobox

### PR DESCRIPTION
**Pull request by K07H**

### CODE REVIEW

**Comment by K07H** [comment]
Please do not delete my work this time, the time I spend on contributing matters. If you want to change my modifications we can talk about it here, or simply do your modifications once my PR is merged. Thank you.

**Comment by miragedmuk** [comment]
> Please do not delete my work this time, the time I spend on contributing matters. If you want to change my modifications we can talk about it here, or simply do your modifications once my PR is merged. Thank you.

I obviously misunderstand how the license stuff works and entitled you to rule on any decisions I make on my own repository.  

As much as I do apreciate any assistance in bug fixes I'm not sure I like your attitude towards forcing new "features" into my own main branch.  The only thing I "deleted" was a user-editable config file which I distribute to my users so they don't have to map all of their own using the app.

I provide all of this for free and don't mind if youd o what you like with your own copy / branch but please drop the attitude and let me decide what I do and don't include in my own stuff.

**Comment by K07H** [comment]
Yeah I might have not said it properlly, English is not my native language. What I mean is if you remove my PR and then recode it yourself, I don't appear as contributor (like it was for the last change I did). If you don't want to add the multiple select it's fine I don't want to force you into anything, I can have my own fork. If you think some stuff needs to be reorganized or changed in my PR we can talk about it here. Thank you

**Comment by miragedmuk** [comment]
Multi-selection will not be added as a feature to my own repository.

The previous PR - you want to appear as a contributor?  Apologies but you made ZERO code changes.  The changes you made  were to a user .json file - one which I maintain for myslef locally and provide the community with to get them started.  One that they can use my app itself to overwrite and map whatever data and names they want?  Get real.

**Pull request closed without merging**
